### ISSUE TITLE
Clarification about stat.birthtime

### ISSUE THREAD

**Issue by fabiospampinato** [ehmicky/portable-node-guide#15]
I've noticed the readme says:

> On the other hand the birthtime and birthtimeMs values are undefined on Unix.

Assuming that you were talking about unix-y systems and not exactly Unix I can't reproduce this on both macOS and Lubuntu:

<img width="576" alt="Screen Shot 2019-03-12 at 16 06 24" src="https://user-images.githubusercontent.com/1812093/54211157-1d373b00-44e1-11e9-991d-0c208af369ea.png">

![Screen Shot 2019-03-12 at 16 05 04](https://user-images.githubusercontent.com/1812093/54211243-4657cb80-44e1-11e9-9654-401e74699d32.png)

So I'm not sure what to take of that. Has this been "fixed" in more recent versions of node? Does it only happen on some specific filesystems? Are you actually talking about _the_ Unix here?

Thanks!

**Comment by ehmicky** [comment]
Thanks for finding this out, this is completely wrong indeed, I am going to fix it.

I do think that `birthtime` is not completely cross-platform. Specifically Linux does not have any concept of `birthtime` so I think Node.js is re-using the `ctime` but that's not really a proper creation timestamp. On Mac and Windows it seems to work just fine though. 

Please correct me if I'm wrong. I am going to make further research to either remove that line or edit it.

You're also probably right that is filesystem-specific. In the guide I have conflated filesystems and OS for simplicity sake though. For example issues I flag NTFS-specific issues as Windows issues, even though NTFS partitions are possible on Linux.

Do you have some ideas?

@allcontributors[bot] please add @fabiospampinato for contributing with fixing the documentation.

**Comment by fabiospampinato** [comment]
@ehmicky I don't really know anything more about this, sorry. It might be a good idea to check what Node is actually doing here by reading its source code.

Btw this is a pretty cool project, thanks for making it!

**Comment by ehmicky** [comment]
After some research I found out that Node.js uses the `stat` field [`stx_btime`](https://github.com/libuv/libuv/blob/45a49688c86bd2afd0fe9e2e85b86ac31ee1e02e/src/unix/fs.c#L1115). This field seems to have been [recently added](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a528d35e8bfcc521d7cb70aaf03e1bd296c8493f) to the Linux kernel, but might have been present before that on BSD and Mac.

However when I try to `touch` a file on Linux, it updates its `birthtime`. It seems to always match the `ctime`. But on Windows and Mac it works.

_Tanti grazii!_ If you like the project, please share it on social media so that other developers can write more cross-platform Node.js, which is something often neglected. :) Also finding errors or missing information is a great way to improve this guide!

**Comment by ehmicky** [comment]
Fixed in https://github.com/ehmicky/portable-node-guide/commit/6712a9a304f62d915871ee6d3de2a25c09e9cf19
